version: '3.8' # 3.8 支援 service_healthy

services:
  mysqlserver:
    container_name: 'mysqlserver'
    platform: linux/amd64
    image: 'mysql:8.0.33'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=water-drop'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=no'
    volumes:
      - './db:/docker-entrypoint-initdb.d'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -p123456 -h 127.0.0.1 -e 'SELECT 1'" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  server:
    build: ../drop-server
    platform: linux/amd64
    container_name: 'server'
    image: 'crpi-yhatmqd5rly143h5.ap-southeast-1.personal.cr.aliyuncs.com/one-react_nestjs/server:v1'
    depends_on:
      mysqlserver:
        condition: service_healthy # 等 MySQL 完全準備好
    ports:
      - '3333:3000'
    volumes:
      - './server:/etc/config'
    restart: always

  pc:
    build: ../water-drop-pc
    platform: linux/amd64
    container_name: 'pc'
    image: 'crpi-yhatmqd5rly143h5.ap-southeast-1.personal.cr.aliyuncs.com/one-react_nestjs/pc:v1'
    depends_on:
      - server
    ports:
      - '4000:80'
    volumes:
      - './nginx:/etc/nginx/conf.d'
    restart: always

  mobile:
    build: ../water-drop-mobile
    platform: linux/amd64
    container_name: 'mobile'
    image: 'crpi-yhatmqd5rly143h5.ap-southeast-1.personal.cr.aliyuncs.com/one-react_nestjs/mobile:v1'
    depends_on:
      - server
    ports:
      - '3000:80'
    volumes:
      - './nginx:/etc/nginx/conf.d'
    restart: always
