services:
  pc:
    build:
      context: ${PC_BUILD_CONTEXT}
    platform: linux/amd64
    container_name: 'pc'
    image: '${ACR_REGISTRY}/one-react_nestjs/pc:v1'
    ports:
      - '4000:80'
    volumes:
      - './nginx:/etc/nginx/conf.d'
    depends_on:
      - server
  mobile:
    build:
      context: ${MOBILE_BUILD_CONTEXT}
    platform: linux/amd64
    container_name: 'mobile'
    image: '${ACR_REGISTRY}/one-react_nestjs/mobile:v1'
    ports:
      - '3000:80'
    volumes:
      - './nginx:/etc/nginx/conf.d'
    depends_on:
      - server
  server:
    build:
      context: ${SERVER_BUILD_CONTEXT}
    platform: linux/amd64
    container_name: 'server'
    image: '${ACR_REGISTRY}/one-react_nestjs/server:v1'
    # 下面的3000是nestjs裡面Nestjs專案裡app.listen(process.env.PORT ?? 3000); 的3000端口，它會實際的對去應用程式端監聽的端口
    ports:
      - '3333:3000'
    volumes:
      - './server:/etc/config'
    depends_on:
      - mysqlserver
  mysqlserver:
    container_name: 'mysqlserver'
    platform: linux/amd64
    image: 'mysql:8.0.33'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=water-drop'
    volumes:
      - './db/myDB:/docker-entrypoint-initdb.d'
      # - './db/water-dropDB:/docker-entrypoint-initdb.d'
