name: Deploy to ECS via SSH only

on:
  push:
    tags:
      - 'v*' # 例如 v1、v1.0.1 等

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v3

      - name: Checkout server repo
        uses: actions/checkout@v3
        with:
          repository: one0910/water-drop-serverSide
          path: drop-server
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Checkout pc repo
        uses: actions/checkout@v3
        with:
          repository: one0910/water-drop-pcSide
          path: water-drop-pc
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Checkout mobile repo
        uses: actions/checkout@v3
        with:
          repository: one0910/water-drop-mobileSide
          path: water-drop-mobile
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: SSH deploy to ECS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USER }}
          key: ${{ secrets.ECS_SSH_KEY }}
          script: |
            echo "✅ 已登入 ECS，開始執行部署腳本..."
            bash /usr/local/bin/deploy-water-drop.sh
