name: Deploy to ECS with Docker + ACR

on:
  push:
    tags:
      - 'v*' # 例如 v1、v1.0.1 等

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            --username ${{ secrets.ACR_USERNAME }} \
            ${{ secrets.ACR_REGISTRY }} --password-stdin

      - name: Build and push docker images
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/one-react_nestjs/server:v1 ./drop-server
          docker build -t ${{ secrets.ACR_REGISTRY }}/one-react_nestjs/pc:v1 ./water-drop-pc
          docker build -t ${{ secrets.ACR_REGISTRY }}/one-react_nestjs/mobile:v1 ./water-drop-mobile

          docker push ${{ secrets.ACR_REGISTRY }}/one-react_nestjs/server:v1
          docker push ${{ secrets.ACR_REGISTRY }}/one-react_nestjs/pc:v1
          docker push ${{ secrets.ACR_REGISTRY }}/one-react_nestjs/mobile:v1

      - name: SSH deploy to ECS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USER }}
          key: ${{ secrets.ECS_SSH_KEY }}
          script: |
            bash /usr/local/bin/deploy-water-drop.sh
